---

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Add public key from elasticsearch
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add elasticsearch apt repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    state: present

- name: Add a PPA for Java 8
  apt_repository:
    repo: ppa:webupd8team/java
    state: present
  # PPA somtimes returns HTTP 503
  retries: 6
  delay: 10

- name: See if the license is accepted
  shell: debconf-show oracle-java8-installer
  changed_when: false
  register: register_debconf_show

- name: Set accepted-oracle-license-v1-1 to true
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  when: "not '* shared/accepted-oracle-license-v1-1: true' in register_debconf_show.stdout_lines"

- name: Install Java 8
  apt:
    name: oracle-java8-installer

- name: Install logstash
  apt:
    name: "{{ logstash_package_name }}"
    state: present

# package logstash 5.1.1 installs logstash-plugin with permission 0775
- name: Make logstash-plugin executable
  file:
    path: "{{ logstash_home }}/bin/logstash-plugin"
    mode: 0755
