---

- name: Install logstash
  yum:
    name: "{{ logstash_package_name }}"
    state: present

# package logstash 5.1.1 installs logstash-plugin with permission 0775
- name: Make logstash-plugin executable
  file:
    path: "{{ logstash_home }}/bin/logstash-plugin"
    mode: 0755
