---

- name: Install logstash
  pkgng:
    name: "{{ logstash_package_name }}"
    state: present

# package logstash-5.0.2 still does not set exec bit
- name: Make logstash-plugin executable
  file:
    path: /usr/local/logstash/bin/logstash-plugin
    mode: 0755
