---

- name: Install logstash
  pkgng:
    name: logstash
    state: present

# package logstash-2.1.0 does not set exec bit
- name: Make plugin executable
  file:
    path: /usr/local/logstash/bin/plugin
    mode: 0755

- name: Make logstash-plugin executable
  file:
    path: /usr/local/logstash/bin/logstash-plugin
    mode: 0755
