---
# tasks file for ansible-role-logstash

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- include: "configure-{{ ansible_os_family }}.yml"

- name: Register installed plugins
  command: "{{ logstash_home }}/bin/logstash-plugin list"
  register: logstash_plugins_list
  changed_when: False

- name: Install plugins
  command: "{{ logstash_home }}/bin/logstash-plugin install {{ item }}"
  with_items: "{{ logstash_plugins_to_install }}"
  when: not ( logstash_plugins_list.stdout | search(item) )
  environment:
    DEBUG: 1
    JARS_DEBUG: true
    JARS_VERBOSE: true

- name: Configure logstash/conf.d
  file:
    path: "{{ logstash_conf_dir }}"
    state: directory

- name: Create logstash configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ logstash_conf_dir }}/{{ item }}"
    mode: 0644
  with_items:
    - input.conf
    - filter.conf
    - output.conf
  notify: Restart logstash

- name: Ensure logstash is running
  service:
    name: "{{ logstash_service_name }}"
    state: started
    enabled: yes

# TODO
# * --allow-unsafe-shutdown
# * install visualvm? https://www.elastic.co/guide/en/logstash/current/pipeline.html
# * logstash 2.3 (auto-reload)
# * reload by sending SIGHUP
# * Managing Throughput Spikes with Message Queueing
# * Managing plugins
