---
# handlers file for ansible-role-logstash

- name: Restart logstash
  # notify this handler only when full restart is required
  service:
    name: "{{ logstash_service_name }}"
    state: restarted
    enabled: yes
  # XXX need to notify "Wait" because:
  #
  # * the rc script "stop" and "start" the daemon
  # * when the daemon starts, but the signal handler to catch HUP has not been
  #   registered, HUP signal terminates the daemon
  #
  # this happens when initially the daemon is configured:
  #
  # * everything for the daemon are configured
  # * the daemon starts
  # * a handler to restart the daemon is called
  # * the rc script stops and starts the daemon
  # * and a handler to reload the daemon is called, sending HUP
  # * the daemon has not registered the handler for HUP
  # * the daemon receives HUP
  # * the daemon terminates and does not start
  # 
  # this causes idempotency_test to fail.
  #
  # the real solution is for the rc script to wait for the daemon to start and
  # returns, i.e. wait for the daemon to listen the port.
  notify: Wait for logstash to start

- name: Wait for logstash to start
  wait_for:
    host: "{{ logstash_api_host }}"
    port: "{{ logstash_api_port }}"
  when: logstash_api_enabled


- name: Reload logstash
  # notify this handler when configuration files has been changed.
  #
  # XXX cannot use /var/run/logstash.pid here. startup script auto-generated by
  # the official package does not create PID file.
  shell: 'kill -HUP `jps -ml | grep -E "org\.jruby\.Main .*logstash\/runner\.rb " | cut -f1 -d" "`'
